### ISSUE TITLE
Why do you take us addresses

### ISSUE THREAD

**Issue by GaelHF** [MRMYSTERY003/sketchpy#15]
?
![image](https://github.com/MRMYSTERY003/sketchpy/assets/118003096/509c02d1-effc-4523-9421-f65ad154cd2e)

**Comment by MRMYSTERY003** [comment]
as i have already mentioned,  we are just gathering the demographics of the users of the sketchpy package, and the code just give a rough location, if you have any doubt you can run it yourself

**Comment by MRMYSTERY003** [comment]
if you have any other doubts you can ask here
