### ISSUE TITLE
Export to mp4/video

### ISSUE THREAD

**Issue by C00reNUT** [MRMYSTERY003/sketchpy#17]
Hello, 
this is a wonderful library, I have had a some fun with it! 

Do you think it would be possible to export the output of drawing animation into mp4 or other video format? It would make for perfect for simple whiteboard animation creator...

**Comment by MRMYSTERY003** [comment]
Hello, Thanks for reaching out.
Happy that you found it wonderful!

Yes, it is possible to export the output of the animation into and mp4 or gif video format using pillow library by capturing each frame and converting to a video format.
I will be happy to include this feature in the next version, Thanks for the Idea.

sample code :

```

import turtle
import pyautogui
import imageio
import time

# Set up the screen and turtle
screen = turtle.Screen()
screen.setup(width=600, height=600)
t = turtle.Turtle()

# Function to draw something with turtle (example)
def draw():
    t.speed(1)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)

# List to store captured frames
frames = []

# Get the position and size of the Turtle window
canvas = screen.getcanvas()
root = canvas.winfo_toplevel()
x0 = root.winfo_rootx() + canvas.winfo_x()
y0 = root.winfo_rooty() + canvas.winfo_y()
width = canvas.winfo_width()
height = canvas.winfo_height()

# Draw and capture frames
draw()  # Start the drawing

# Capture frames while drawing
for _ in range(36):
    t.left(10)
    t.forward(10)
    # Capture the screen dynamically based on the Turtle window position and size
    img = pyautogui.screenshot(region=(x0, y0, width, height))
    frames.append(img)
    time.sleep(0.1)  # Adjust the sleep time for smoother or faster capture

# Save the captured frames as a GIF or video
frames[0].save('turtle_animation.gif', save_all=True, append_images=frames[1:], duration=100, loop=0)

```

**Comment by C00reNUT** [comment]
Thank you very much for quick response! It would be very nice if you could add this feature in the future release, I think it is quite useful for more people than just me.

Thank you!
