### ISSUE TITLE
error with svg files

### ISSUE THREAD

**Issue by progressify** [MRMYSTERY003/sketchpy#4]
this is my code:

```
from sketchpy import canvas

if __name__ == '__main__':
    pen = canvas.sketch_from_svg("2022_04_06.svg")
    pen.draw()
```

this is the output in console:

```
python.exe main.py
loading data
100%|██████████| 25/25 [00:09<00:00,  2.60it/s]
svg data loaded
42 40
```

but I see this small window and it no draw anithing:

![image](https://user-images.githubusercontent.com/11472632/161936802-ea0f4eab-e144-4009-9695-e77fefd9708b.png)

this is the file that I have used:

![2022_04_06](https://user-images.githubusercontent.com/11472632/161936899-b69fb5de-d199-48c0-ac97-1fe08e2c51bb.svg)

I have generated it with this site: https://svgconvert.com/#/

**Comment by MRMYSTERY003** [comment]
maximize the turtle screen, and this bug will be rectified on next version
