### ISSUE TITLE
Drawing from raw image

### ISSUE THREAD

**Issue by stlashi** [MRMYSTERY003/sketchpy#6]
Thanks for the fun package! The current sample code provided for the **drawing from raw image** is as below - should the last line be obj.draw(threshold=270) instead? 

```
    from sketchpy import canvas
    obj = canvas.sketch_from_image('IMAGE PATH')
    obj = draw(threshold = 127)
```

**Comment by MRMYSTERY003** [comment]
having high threshold results in high processing time, so by default it is set to 127, you can anyway set it to 270
